### ISSUE TITLE
Captcha does'nt redraw also refresh button is not showed

### ISSUE THREAD

**Issue by MG1376** [VahidN/DNTCaptcha.Blazor#8]
I have this code to redraw your captcha:

```
else if (!string.IsNullOrWhiteSpace(dntModel.CaptchaText)
    && dntModel.CaptchaText == dntModel.EnteredCaptchaText)
{
    await LoginUser();
    if (!auth.CurrentUser.IsAuthenticated)
    {
        dntModel = new DNTCaptchaModel();
        dntModel.CaptchaText = string.Empty;
        dntCaptcha.Value = "";
        model.Password = "";                    
    }
}
```
And I have this model:

```
DNTCaptchaModel dntModel = new DNTCaptchaModel();
public class DNTCaptchaModel
{
    [Required]
    [Compare(nameof(CaptchaText), ErrorMessage = "The entered `Security Number` is not correct.")]
    public string EnteredCaptchaText { set; get; }

    public string CaptchaText { set; get; }
}
```
No refresh occures after executing these codes, I have debugged the codes ans see these codes are executed. Also no refresh button shows beside this captcha. I use .Net 8 and Blazor webassembly.

**Comment by VahidN** [comment]
How did you define your page in .NET 8?

**Comment by MG1376** [comment]
This is the Markup part:

 ```
@if (firstSignIn == false) // second and above sign in try
{
<MudBlazor.MudStack Row="true" AlignItems="MudBlazor.AlignItems.Center"
                     Justify="MudBlazor.Justify.FlexStart" Spacing="3">
     <MudBlazor.MudTextField T="string" Label="کد امنیتی" Required="true"
                             @bind-Value="dntModel.EnteredCaptchaText" Immediate="false">
     </MudBlazor.MudTextField>
     <DntInputCaptcha @bind-Value="dntModel.CaptchaText" DisplayMode="DisplayMode.ShowDigits"
                      Min="10000" Max="99999"
                      @ref="dntCaptcha">
     </DntInputCaptcha>
 </MudBlazor.MudStack>
}
```
When submit button is clicked, the above codes inside 'else if' executes.  The captcha is at first invisible and if user enters invalid password, in the second try, the captcha becomes visible. model is there at first but only the captcha on page load is invisible and after users first login try becomes visible.

**Comment by VahidN** [comment]
Have you tried setting the `RefreshButtonClass` and `ShowRefreshButton` parameters? [It uses bootstrap's icons](https://github.com/VahidN/DNTCaptcha.Blazor/blob/main/src/DNTCaptcha.Blazor.WasmSample/Client/Pages/Components/Login.razor#L70) by default. It's defined [here](https://github.com/VahidN/DNTCaptcha.Blazor/blob/main/src/DNTCaptcha.Blazor.WasmSample/Client/libman.json#L12). You can change it to any other font-icon library if you want and then set the `RefreshButtonClass` parameter.

**Comment by MG1376** [comment]
yes. I tried these two classes, refresh button is not showing, but is hidden and when I click on its place it works, but is hidden. The main problem I have is: the captcha does not refresh when I do this:
```
 dntModel = new DNTCaptchaModel();
 dntModel.CaptchaText = string.Empty;
```
I think, since the captcha is invisible at first load, and becomes visible after an interaction, this problem occurs.

**Comment by VahidN** [comment]
I can't reproduce your problem. I added a new sample called [InvisibleCaptchaAtFirst.razor](https://github.com/VahidN/DNTCaptcha.Blazor/blob/main/src/DNTCaptcha.Blazor.WasmSample/Client/Pages/InvisibleCaptchaAtFirst.razor#L38) and it works fine. [You can see and run it here](https://vahidn.github.io/DNTCaptcha.Blazor/Invisible-Captcha-At-First).
About .NET 8x: There are `@rendermode`s and interactivity that you should be aware of. Yes, It's a bit different (All components use the Static render mode as default, that's why interactive render mode **_must be_** specified explicitly.) and that's why I asked, how did you define your page in .NET8x, because I wanted to know, have you added a correct `@rendermode`? [You can read more about it here in Persian](https://www.dntips.ir/post/3488/%d8%a8%d8%b1%d8%b1%d8%b3%db%8c-%d8%aa%d8%ba%db%8c%db%8c%d8%b1%d8%a7%d8%aa-blazor-8x-%d9%82%d8%b3%d9%85%d8%aa-%d8%b3%d9%88%d9%85-%d8%b1%d9%88%d8%b4-%d8%a7%d8%b1%d8%aa%d9%82%d8%a7%d8%a1-%d8%a8%d8%b1%d9%86%d8%a7%d9%85%d9%87%e2%80%8c%d9%87%d8%a7%db%8c-blazor-server-%d9%82%d8%af%db%8c%d9%85%db%8c-%d8%a8%d9%87-%d8%af%d8%a7%d8%aa-%d9%86%d8%aa-8#comment-19326).
